version: '3.4'

services:
  homelibrary:
    image: homelibrary
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./src:/usr/app/src
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - homelibrary-net
    depends_on:
      - postgres
    restart: always
    ports:
      - ${PORT}:${PORT}
  postgres:
    image: postgres
    build:
      context: .
      dockerfile: ./src/database/Dockerfile
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - homelibrary-net
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
volumes:
  db-data:
networks:
  homelibrary-net:
    driver: bridge
